version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - aws cloudformation package --template-file template.yml --s3-bucket sample-aws-codepipeline-bucket --output-template-file outputTemplate.yaml
      - aws cloudformation create-stack --stack-name p215-ncw-barath-lambdaStack --template-url https://sample-aws-codepipeline-bucket.s3.ap-northeast-1.amazonaws.com/emptyStack.yml || true
artifacts:
  files:
    - template.yaml
    - outputTemplate.yaml