AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda

Resources:
  P215NcwBarathLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      CodeUri: ./Lambda
      Runtime: python3.8
      AutoPublishAlias: live
      Description: CI/CD demo
      MemorySize: 128
      Timeout: 60
      DeploymentPreference:
        Type: Linear10PercentEveryMinute
        Hooks:
          PreTraffic: !Ref PreTrafficHook
      Events:
        !Ref P215NcwBarathDemoAPI
      
      Environment:
        Variables:
          Region: !Sub {AWS::Region}

  P215NcwBarathDemoAPI:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: "api"
  Resource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      RestApiId: !Ref P215NcwBarathDemoAPI
      ParentId: !GetAtt P215NcwBarathDemoAPI.RootResourceId  
      PathPart: !Ref P215NcwBarathLambda
  LambdaPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !Ref P215NcwBarathLambda
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
  ResourceMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      RestApiId: !Ref P215NcwBarathDemoAPI
      ResourceId: !Ref Resource
      AuthorizationType: "None"
      HttpMethod: "GET"
      Integration:
        Type: "AWS"
        IntegrationHttpMethod: "GET"
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${P215NcwBarathLambda}/invocations"
    DependsOn: "LambdaPermission"
        
    
  PreTrafficHook:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./Lambda
      FunctionName: 'PreTrafficHook'
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action: 
              - "codedeploy:PutLifecycleEventHookExecutionStatus"
            Resource:
              !Sub 'arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*'
        - Version: "2012-10-17"
          Statement: 
          - Effect: "Allow"
            Action: 
              - "lambda:InvokeFunction"
            Resource: !Ref P215NcwBarathLambda.Version
      DeploymentPreference:
        Enabled: false
      Timeout: 5
      Environment:
        Variables:
          NewVersion: !Ref P215NcwBarathLambda.Version     