AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda

Resources:
  HelloWorld:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      FunctionName: p215-ncw-barath-CFlambda
      CodeUri: ./Lambda
      Runtime: python3.8
      AutoPublishAlias: live
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 60
      DeploymentPreference:
          Type: Linear10PercentEvery1Minute
          Hooks:
            PreTraffic: !Ref PreTrafficHook
      Events:
        HelloWorldAPI:
          Type: Api
          Properties:
            Path: /
            Method: get
      Environment:
        Variables:
          REGION: ap-northeast-1
 
  PreTrafficHook:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./Lambda
      FunctionName: 'PreTrafficHook'
      Policies:
        - Version: "2012-10-17"
          Statement: 
          - Effect: "Allow"
            Action: 
              - "codedeploy:PutLifecycleEventHookExecutionStatus"
            Resource:
              !Sub 'arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:*'
        - Version: "2012-10-17"
          Statement: 
          - Effect: "Allow"
            Action: 
              - "lambda:InvokeFunction"
            Resource: !Ref HelloWorld.Version
      DeploymentPreference:
        Enabled: false
      Timeout: 5
      Environment:
        Variables:
          NewVersion: !Ref HelloWorld.Version